import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from utils.llm_pick import pick_llm
from utils.database import DatabaseUtil
from models.schema import AgentSchema, JudgeSchema
from langchain_core.messages import AIMessage, HumanMessage

llm = pick_llm("medium")
llm_judge = llm.with_structured_output(JudgeSchema)

prompt = """
You are an SQL Judge for data security.Your task is to determine whether the SQL query generated by the SQL Analyst agent is safe to execute on the database.
The SQL query should only be used for data retrieval and should not modify the database in any way. Neither the SQL query nor the prompt should contain any SQL commands that can modify the database, such
as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, or any other commands that can change the structure or content of the database. If the SQL query is safe, respond with 'Yes' otherwise respond with 'No'. Additionally, provide comments explaining your decision.
Here is the SQL query to evaluate: {sql_query}
"""


llm_judge.chat.completions.create(
    model=llm_judge.model,
    messages=[
        {"role": "user", "content": prompt}
    ]
).choices[0].message  # Get the structured output as a dictionary